# db/setup.py
# Run this once to create the database and all tables

import mysql.connector
from db.config import DB_CONFIG

def get_connection(with_db=True):
    """Get a MySQL connection. If with_db=False, connects without selecting DB (used for DB creation)."""
    config = DB_CONFIG.copy()
    if not with_db:
        config.pop("database", None)
    return mysql.connector.connect(**config)

def setup_database():
    """Create database and all required tables if they don't exist."""
    try:
        # Step 1: Create the database itself
        conn = get_connection(with_db=False)
        cursor = conn.cursor()
        cursor.execute(f"CREATE DATABASE IF NOT EXISTS {DB_CONFIG['database']}")
        cursor.execute(f"USE {DB_CONFIG['database']}")
        print(f"✅ Database '{DB_CONFIG['database']}' ready.")

        # ─── TABLE 1: security_alerts ───────────────────────────────
        # Stores every alert generated by any module with risk score - ugale 
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS security_alerts (
                id            INT AUTO_INCREMENT PRIMARY KEY,
                alert_level   ENUM('critical','high','medium','low','info') NOT NULL,
                alert_message TEXT NOT NULL,
                module_source VARCHAR(50) NOT NULL,   -- which module generated it
                risk_score    INT DEFAULT 0,           -- score at time of alert
                is_resolved   BOOLEAN DEFAULT FALSE,
                created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
                resolved_at   DATETIME NULL
            )
        """)
        print("✅ Table 'security_alerts' ready.")

        # ─── TABLE 2: risk_score_history ────────────────────────────
        

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS risk_score_history (
                id           INT AUTO_INCREMENT PRIMARY KEY,
                risk_score   INT NOT NULL,
                risk_label   VARCHAR(20) NOT NULL,   -- SECURE / MODERATE / HIGH RISK
                open_ports   INT DEFAULT 0,
                failed_logins INT DEFAULT 0,
                fim_modified  INT DEFAULT 0,
                network_devices INT DEFAULT 0,
                recorded_at  DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ Table 'risk_score_history' ready.")

        # ─── TABLE 3: fim_logs ──────────────────────────────────────

        cursor.execute("""
            CREATE TABLE IF NOT EXISTS fim_logs (
                id              INT AUTO_INCREMENT PRIMARY KEY,
                file_path       VARCHAR(500) NOT NULL,
                event_type      ENUM('added','modified','deleted','unchanged') NOT NULL,
                original_hash   VARCHAR(64) NULL,    -- SHA-256 baseline
                current_hash    VARCHAR(64) NULL,    -- SHA-256 at check time
                size_change     INT DEFAULT 0,       -- bytes changed
                checked_at      DATETIME DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ Table 'fim_logs' ready.")

        conn.commit()
        cursor.close()
        conn.close()
        print("\n🎉 Database setup complete! All tables created.")
        return True

    except mysql.connector.Error as e:
        print(f"\n❌ MySQL Error: {e}")
        print("\n👉 Make sure:")
        print("   1. MySQL is installed and running")
        print("   2. Username/password in db/config.py are correct")
        print("   3. Run: net start MySQL  (Windows) or  sudo service mysql start  (Linux)")
        return False

if __name__ == "__main__":
    setup_database()
